// DO NOT EDIT! generated by ./autogen

#ifndef kat_h
#define kat_h

#include "kat_namespace.h"

#define known_answer_tests 100
extern const int8_t alice_private_key_kats[known_answer_tests][primes_num];
extern const int8_t bob_private_key_kats[known_answer_tests][primes_num];
extern const fp alice_public_key_kats[known_answer_tests];
extern const fp bob_public_key_kats[known_answer_tests];
extern const fp alice_shared_secret_kats[known_answer_tests];
extern const fp bob_shared_secret_kats[known_answer_tests];

#endif
