// DO NOT EDIT! generated by ./autogen

#ifndef primes_h
#define primes_h

#include "primes_namespace.h"

#if BITS == 505
#define primes_num 74
#define primes_batches 13
#define primes_maxbatchboundplussize 27
#elif BITS == 512
#define primes_num 74
#define primes_batches 15
#define primes_maxbatchboundplussize 25
#elif BITS == 1024
#define primes_num 131
#define primes_batches 22
#define primes_maxbatchboundplussize 18
#else
#error BITS must be 505 or 512 or 1024
#endif

extern const long long primes[primes_num];
extern const long long primes_dac[primes_num];
extern const long long primes_daclen[primes_num];
extern const long long primes_batchsize[primes_batches];
extern const long long primes_batchstart[primes_batches];
extern const long long primes_batchstop[primes_batches];
extern const long long primes_batchbound[primes_batches];
extern const long long primes_batchmaxdaclen[primes_batches];

#endif
